updates error handling in test script

diff --git a/portforward-test b/portforward-test
--- a/portforward-test
+++ b/portforward-test
@@ -35,9 +35,11 @@ set +e
 # $ kubectl port-forward -v=4 nginx ${LOCAL_PORT_1}:${REMOTE_PORT_1} ${LOCAL_PORT_2}:${REMOTE_PORT_2}
 
 temp_dir=`mktemp -d`
+errors_dir=`mktemp -d`
 echo "Starting port forward test: ${LOCAL_PORT_1}:${REMOTE_PORT_1} ${LOCAL_PORT_2}:${REMOTE_PORT_2}"
 echo
 echo "Temp Dir: $temp_dir"
+echo "Errors Dir: $errors_dir"
 echo
 
 for (( i=1 ; i<=$NUM_PORT_FORWARDS ; i++ )); 
@@ -60,9 +62,29 @@ do
     curl -s http://localhost:${LOCAL_PORT_2}/basic-large.html > ${output_4}
     # Validate the output files are valid.
     diff -q ${output_1} ${GOLDEN_FILE_1}
+    if [ $? -ne 0 ];
+    then
+	mv ${output_1} ${errors_dir}
+    fi
+
     diff -q ${output_2} ${GOLDEN_FILE_1}
+    if [ $? -ne 0 ];
+    then
+	mv ${output_2} ${errors_dir}
+    fi
+
     diff -q ${output_3} ${GOLDEN_FILE_2}
+    if [ $? -ne 0 ];
+    then
+	mv ${output_3} ${errors_dir}
+    fi
+
     diff -q ${output_4} ${GOLDEN_FILE_3}
+    if [ $? -ne 0 ];
+    then
+	mv ${output_4} ${errors_dir}
+    fi
+
     # Clean up
     rm -f ${output_1}
     rm -f ${output_2}
